### ISSUE TITLE
make `--exclude-use-default` configurable

### ISSUE THREAD

**Issue by jschwinger23** [fatih/vim-go#2501]
### What did you do? (required: The issue will be **closed** when not provided)
composed a golangci-lint config file under the project root dir but failed to make it work

```
# .golangci.yml
linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - golint

issues:
  exclude-use-default: true
```

### What did you expect to happen?
it's expected that `exported method should have comment or be unexported` is hidden because I specified `exclude-use-default: true` in config file.

### What happened instead?
error `exported method should have comment or be unexported` still raised

#### vim-go version:
silent! let g:plugs['vim-go'].commit = '1946131'

####  `vimrc` you used to reproduce (use a *minimal* vimrc with other plugins disabled; do not link to a 2,000 line vimrc):
<details><summary>vimrc</summary><br><pre>
let g:go_metalinter_command='golangci-lint'
let g:go_metalinter_autosave = 1
let g:go_fmt_command = "goimports"
let g:go_def_mapping_enabled = 0

</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.1 (2018 May 18, compiled Jul 21 2019 22:54:00)
macOS version
Included patches: 1-1722

#### Go version (`go version`):
go version go1.12.6 darwin/amd64

#### Go environment
<details><summary><code>go env</code> Output:</summary><br><pre>

</pre></details>
