### ISSUE TITLE
The `g:go_gopls_gofumpt` setting doesn't seem to work

### ISSUE THREAD

**Issue by vendion** [fatih/vim-go#3014]
### What did you expect to happen?

When vim-go executes the set `g:go_fmt_command` (in my case set to `gopls`) and the `g:go_gopls_gofumpt` setting is set for the code to be formatted based on `gofumpt` so that when `golang-ci` is ran it doesn't find such problems.

### What happened instead?

After vim-go runs gopls to format the file if `golang-ci` is also ran on that same file it reports the following "File is not `gofumpt`-ed (gofumpt)"

#### vim-go version:

v1.24

####  `vimrc` you used to reproduce:

<details><summary>
packadd gotests-vim

" gopls settings
let g:go_gopls_gofumpt = 1
let g:go_gopls_staticcheck = 1
let g:go_gopls_analyses = 1
let g:go_gopls_complete_unimported = 1
let g:go_gopls_matcher = 'fuzzy'
let g:go_gopls_use_placeholders = 1

" Go fmt settings
let g:go_fmt_command = "gopls"
"let g:go_fmt_autosave = 1
let g:go_imports_mode = 'gopls'

" Go metalinter settings
let g:go_metalinter_autosave = 1
let g:go_metalinter_command='gopls'

" Code highlighting settings
let g:go_highlight_types = 1
let g:go_highlight_fields = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1
let g:go_highlight_extra_types = 1

" Terminal settings
let g:go_term_enabled = 1
let g:go_term_mode = "split"
let g:go_term_reuse = 1

" Code analysis settings
let g:go_auto_type_info = 1
let g:go_list_type = "quickfix"
let g:go_auto_sameids = 1
"let g:go_def_mapping_enabled = 0

" Misc vim-go settings
let g:go_template_use_pkg = 1
</summary><br><pre>

</pre></details>

#### Vim version (first three lines from `:version`):
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Sep 14 2020 18:41:48)                                          
Included patches: 1-1684
Compiled by Arch Linux

#### Go version (`go version`):
go version go1.15.2 linux/amd64

#### Go environment
<details><summary><code>go env</code> Output: GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vendion/.cache/go-build"
GOENV="/home/vendion/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/vendion/gocode/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/vendion/gocode"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/usr/lib/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build733169150=/tmp/go-build -gno-record-gcc-switches"
</summary><br><pre>

</pre></details>

#### gopls version
<details><summary><code>gopls version</code> Output: golang.org/x/tools/gopls master
    golang.org/x/tools/gopls@(devel)
</summary><br><pre>

</pre></details>

**Comment by bhcleek** [comment]
do you have an example file that I can test this with?

**Comment by vendion** [comment]
Here is a simple example that I can reproduce this with

```go
package main

import (
	"log"
	"os"
)

func main() {
	_, err := os.Open("foo")

	if err != nil {
		log.Fatal(err)
	}
}
```

Running `golangci-lint` with the following config produces the error

```toml
[run]
  concurrency = 4
  deadline = "5m"
  skip-dirs = ['static/wasm']
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

[linters]
  enable-all = true
  disable = [
    "maligned",
    "lll",
    "dupl",
    "scopelint",
    "gomnd",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = []
```

Error: `main.go:10: File is not `gofumpt`-ed (gofumpt)`
