### ISSUE TITLE
GoMetaLinter supports root file config `.golangci.yaml`

### ISSUE THREAD

**Issue by martinsrso** [fatih/vim-go#3087]
# What did you do? 
I would like to use `.golang-ci.yaml` found in the project's root folder in the `:GoMetaLinter` command.

### What did you expect to happen?
I would like to use .golang-ci.yaml found in the project's root folder in the GoMetaLinter command.

Currently, the command only considers the package straight from the file. As an example: the project is in the path `/usr/ projects/goproj` and it is the directory where I opened neovim. In the folder hierarchy there is a `workers` package. Staying like this:
`goproj> workers> file1.go, file2.go`
`goproj> main.go`
`goproj> .golangci.yaml`

I have the buffer open in `file1.go`. If I run `:GoMetaLinter` it will not take the project root settings and will only run for package workers.

### What happened instead?
It only ran for package `workers` with the default configuration in my case.

#### vim-go version:

<details><summary>vim-go version</summary><br><pre>
1.24
</pre></details>

####  `vimrc` you used to reproduce:

<details><summary>vimrc</summary><br><pre>
 -- disable vim-go snippet engine
    vim.g.go_snippet_engine = ""

    -- vim-go vars
    vim.g.go_fmt_command = "goimports"
    vim.g.go_list_type = "quickfix"
    vim.g.go_addtags_transform = "camelcase"
    vim.g.go_metalinter_enabled = {}
    vim.g.go_metalinter_autosave_enabled = {}
    vim.g.go_auto_type_info = 1
</pre></details>

#### Go version (`go version`):

<details><summary>go version</summary><br><pre>
1.15.4
</pre></details>

#### Go environment
<details><summary><code>go env</code> 
</summary><br><pre>

GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/rafael.martins/Library/Caches/go-build"
GOENV="/Users/rafael.martins/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOINSECURE=""
GOMODCACHE="/Users/rafael.martins/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Users/rafael.martins/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/Cellar/go/1.15.4/libexec"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.15.4/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0b/160561q94fl6grsd9pvfn9x80000gp/T/go-build008007327=/tmp/go-build -gno-record-gcc-switches -fno-common"
</pre></details>

#### gopls version
<details><summary><code>gopls version</code> </summary> <br><pre>

 v0.5.3
</pre></details>

**Comment by bhcleek** [comment]
Vim-go runs golangci-lint with the working directory set to the directory that contains the active buffer. According to https://golangci-lint.run/usage/configuration/#config-file, what you're doing should work as far as I can tell. You can use use `let l:go_debug=['shell-commands']` to see exactly what command vim-go is using and try it for yourself at the commandline.

**Comment by martinsrso** [comment]
It's running this one:
```
vim-go: job command: ['/Users/rafael.martins/go/bin/golangci-lint', 'run', '--print-issued-lines=false', '--build-tags', '', '--exclude-use-default=false', '/Users/rafael.martins/projects/goproj/workers']
```

When I run inside the same folder but shell directly the verbose result is this.
```
go run github.com/golangci/golangci-lint/cmd/golangci-lint run --timeout 10m --verbose
INFO [config_reader] Config search paths: [./ /Users/rafael.martins/projects/goproj /Users/rafael.martins/projects/goproj/workers /Users/rafael.martins/projects /Users/rafael.martins /Users /]
INFO [config_reader] Used config file .golangci.yml
```

**Comment by bhcleek** [comment]
Maybe I'm misunderstanding what you want to happen. When I first read your issue, I thought you were saying that you want the `golangci.yml` in `/Users/rafael.martins/projects/goproj` to be used when the active buffer was from `/Users/rafael.martins/projects/goproj/workers`. After re-reading, though, I think you might be asking for `/Users/rafael.martins/projects/goproj` to be the directory that is linted instead of `/Users/rafael.martins/projects/goproj/workers`. Can you clarify for me?

**Comment by martinsrso** [comment]
Exactly the second option, I would like an open buffer in `/goproj/workers/file1.go` to linter this file but respecting the configuration of golangci in the root directory. It was clear? 
Sorry for my English.

**Comment by bhcleek** [comment]
No worries on the language front; I'm happy to work through any language difficulties.

From what I can tell, you are seeing the behavior that you've asked for: the package in `/goproj/workers` is being linted and it's golangci-lint would use the `/goproj/.golangci.yml` to control its behavior.

**Comment by martinsrso** [comment]
Exactly.

**Comment by bhcleek** [comment]
If it's working as you expect, then shall we close this?

**Comment by martinsrso** [comment]
No, it's not using the configuration for the file1.go file lint when opened. It should run the project file that I opened when I gave the nvim command to open project.

**Comment by bhcleek** [comment]
Ok, I'm confused. You're linting `/goproj/workers`. `golangci-lint` will use the `golangci.yml` file that's closest to that directory. What makes you think that it's not using `/goproj/.golangci.yml` ? Do you have a `/goproj/workers/.golangci.yml`?

**Comment by martinsrso** [comment]
Exact it is not using the nearest one. There is no  exist `.golangci.yml` in `/goproj/workers/`

**Comment by bhcleek** [comment]
> I would like to use .golang-ci.yaml found in the project's root folder in the :GoMetaLinter command.

The project as you've described it is at `/Users/rafael.martins/projects/goproj`, and it contains a `.golangci.yml` file, and that's the config that golangci-lint is using.

So given this scenario:
1. `/Users/rafael.martins/projects/goproj/.golangci.yml` exists
2. `/Users/rafael.martins/projects/goproj/workers/.golangci.yml` does _not_ exists.
3. You run `:GoMetaLinter` in `/Users/rafael.martins/projects/goproj/workers`

What config do you expect golangci-lint to use?

**Comment by martinsrso** [comment]
![image](https://user-images.githubusercontent.com/11994788/99115061-9cdbae00-25d0-11eb-92f0-fe77f40869fc.png)

`~/sandbox/goproj $ nvim`

Opens file with `:e workers/file1.go`
Runs `:GoMetaLinter`

I would expect you to use the `.golanci.yml` from the folder I used nvim. But he doesn't use him.

**Comment by bhcleek** [comment]
What evidence do you see that it's _not_ using `~/sandbox/goproj/.golangci.yml`? From everything that I see, that's the config file that `golangci-lint` would use when it lints `~/sandbox/goproj/workers`.

To be clear, the working directory the vim-go uses to run the command will _always_ be set to the directory that contains the file for the active buffer. That's a separate question from which config file `golangci-lint` will use.

**Comment by martinsrso** [comment]
the evidence that running golancg-ci through makefile and go-vim the results are different because I take some rules out of lint.

**Comment by bhcleek** [comment]
Can you be more specific? I have no idea what's in your Makefile, what you're seeing when you run it there, or what you're seeing when you run `:GoMetalinter`.

**Comment by martinsrso** [comment]
```
# GolangCI-Lint configuration.
# See https://github.com/golangci/golangci-lint#config-file for reference.

run:
  skip-dirs:
    - vendor

linters-settings:
  lll:
    line-length: 140
    tab-width: 4
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    # - funlen
    # - gochecknoglobals
    # - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    # - gocyclo
    # - godox
    - gofmt
    - goimports
    - golint
    # - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # - wsl

issues:
  exclude-rules:
    # Exclude crypto/md5 from security linter
    - text: "weak cryptographic primitive"
      linters:
        - gosec
```

My `.golanci.yaml`. 

![Uploading image.png…](Result of `:GoMetalinter` on buffer workers/file2.go)

![Uploading image.png…](Result go run)
