### ISSUE TITLE
Cannot use dlv with container

### ISSUE THREAD

**Issue by raphink** [fatih/vim-go#3147]
I'm trying to use `dlv` in a container. 

I'm creating a container with:

```Dockerfile
FROM golang:1.15

WORKDIR /src
EXPOSE 40000 8080

RUN go get github.com/derekparker/delve/cmd/dlv

RUN mkdir /.cache \
    && chown -R 1000.0 /.cache
USER 1000

ENTRYPOINT [ "dlv", "debug", ".", "--listen=:40000", "--headless=true", "--api-version=2", "--log", "--" ]
CMD []
```

Then launching it with:

```yaml
version: '3'
services:
  backend:
    image: raphink/containers-course-app:go_debug
    build:
      context: .
      dockerfile: Dockerfile.debug
    volumes:
      - .:/src
    ports:
      - "8080:8080"
      - "40000:40000"
    security_opt:
      - "seccomp:unconfined"
```

I'm able to use this container for debug in VSCode by connecting to port 40000, but vim-go uses `dlv attach` instead of `connect` so I can't do that.

Trying to attach to the PID of the container fails with "operation not permitted".

So I'm trying to start a local `dlv` process as a proxy:

```
dlv connect 127.0.0.1:40000 --headless --api-version 2 --log --log-output rpc,debugger
```

And then use `GoDebugAttach <pid>` with the PID of the proxy dlv.

I then get:

```
vim-go: could not toggle breakpoint: could not find file /home/raphink/src/github.com/camptocamp/containers-course-app/backend/go/main.go                                            
```

I still get the same error if I make sure to use the same path inside the container.

What could this error be?
